spring:
  application:
    name: dynamic-datasource-core
    #Redis的配置
  redis:
    host: 127.0.0.1 # Redis服务器地址
    database: 3 # Redis数据库索引（默认为0）
    port: 16379 # Redis服务器连接端口
    password: SbtyMveYNfLzTks7H0apCmyStPzWJqjy # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
      timeout: 3000ms # 连接超时时间（毫秒）

# 服务端口
server:
  port: 9990

# 默认动态数据源配置
dynamic-datasource:
  default:
    url: jdbc:mysql://localhost:3306/lamp_defaults?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&serverTimezone=UTC
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver

#mybatis-plus配置控制台打印完整带参数SQL语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 自定义redis key
redis:
  key:
    prefix:
      authCode: "dynamic-datasource:authCode:"
    expire:
      authCode: 120 # 验证码超期时间








